delete [dbo].[Classes]

SET IDENTITY_INSERT [dbo].[Classes] ON
insert into [dbo].[Classes](Id , ClassName) values (1,N'اصلی')
insert into [dbo].[Classes](Id , ClassName) values (2,N'پت شاپ')
insert into [dbo].[Classes](Id , ClassName) values (3,N'درمانگاه')
insert into [dbo].[Classes](Id , ClassName) values (8,N'املاک')
insert into [dbo].[Classes](Id , ClassName) values (10,N'خودرو')
insert into [dbo].[Classes](Id , ClassName) values (11,N'پوشاک')
insert into [dbo].[Classes](Id , ClassName) values (12,N'ورزشی')
insert into [dbo].[Classes](Id , ClassName) values (13,N'پمپ بنزین')
insert into [dbo].[Classes](Id , ClassName) values (14,N'رستوران')
insert into [dbo].[Classes](Id , ClassName) values (15,N'کافه')
insert into [dbo].[Classes](Id , ClassName) values (16,N'شیرینی‌فروشی')
insert into [dbo].[Classes](Id , ClassName) values (17,N'آرایشگاه مردانه')
insert into [dbo].[Classes](Id , ClassName) values (18,N'کارواش')
insert into [dbo].[Classes](Id , ClassName) values (25,N'میوه فروشی')
insert into [dbo].[Classes](Id , ClassName) values (26,N'سوپر مارکت')
insert into [dbo].[Classes](Id , ClassName) values (27,N'نانوایی')
insert into [dbo].[Classes](Id , ClassName) values (28,N'خشکشویی')
insert into [dbo].[Classes](Id , ClassName) values (29,N'گل فروشی')
insert into [dbo].[Classes](Id , ClassName) values (30,N'آرایشگاه زنانه')
insert into [dbo].[Classes](Id , ClassName) values (31,N'آتلیه')
insert into [dbo].[Classes](Id , ClassName) values (32,N'الکتریکی')
insert into [dbo].[Classes](Id , ClassName) values (33,N'ابزارفروشی')
insert into [dbo].[Classes](Id , ClassName) values (34,N'کلیدسازی')
insert into [dbo].[Classes](Id , ClassName) values (35,N'کپی و پرینت')
insert into [dbo].[Classes](Id , ClassName) values (36,N'آبمیوه بستنی')
insert into [dbo].[Classes](Id , ClassName) values (37,N'موبایل کامپیوتر')
SET IDENTITY_INSERT [dbo].[Classes] Off